### PR TITLE
mikro-orm migrations: Fix detection of .ts files when .snapshot-main.json exists

### PR DESCRIPTION
**Pull request by nsams**
TODO: evaluate if we should use the snapshot feature (if yes: add snapshot to git, if no: disable snapshot generation)

### CODE REVIEW

**Review by johnnyomair — APPROVED** [review]

**Comment by johnnyomair** [comment]
In our customer projects we decided to disable the snapshot feature as pending migrations would not be executed by our migrate console job. We could look into that, however.

**Comment by nsams** [comment]
so we should also disable for demo?

(I would keep this change though)

**Comment by johnnyomair** [comment]
> so we should also disable for demo?

Yes. Either that, or fix the migrate console job.

> (I would keep this change though)

Yes

**Comment by nsams** [comment]
@johnnyomair done (in this PR)

**Review by johnnyomair — APPROVED** [review]

**Pull request merged**
