### PR TITLE
Fix fixtures

### PR DESCRIPTION
**Pull request by thomasdax98**
## Problem:

Our fixtures are currently broken. You always get this error when executing them:

Bildschirmfoto 2023-12-14 um 17 02 52

The problem is that a required `userGroup` field is added to `PageTreeNode` in Demo:

https://github.com/vivid-planet/comet/blob/99e0c57cc8ef542befd74d5b8ad9cf71058570e1/demo/api/src/page-tree/entities/page-tree-node.entity.ts#L26-L28

https://github.com/vivid-planet/comet/blob/1c098e4d0f23946c0fd543856c8f0aa897b83b82/demo/api/src/page-tree/dto/page-tree-node.input.ts#L7-L12

We don't provide a userGroup in the fixtures and it didn't strike because the typing of `PageTreeService.createNode()` is wrong. The input is typed with `PageTreeNodeBaseCreateInput`

https://github.com/vivid-planet/comet/blob/b73eb4c34c70c694fc8b267ce330af5959c50e7b/packages/api/cms-api/src/page-tree/page-tree.service.ts#L33

but the actual input type can be defined in the application and is passed to the resolver via a factory:

https://github.com/vivid-planet/comet/blob/46bced34cbb9ec02de6dd462bd9111a6be7898b7/packages/api/cms-api/src/page-tree/createPageTreeResolver.ts#L35

### -> So actually the typing in the `PageTreeService` is wrong and we need to fix that

I now circumvented this by using ts-ignore. 
But I think we need a solution to get the typing right. I'm however not sure what the best way to do this is.

### CODE REVIEW

**Comment by johnnyomair** [comment]
Could you please use `@ts-expect-error` instead of `@ts-ignore`? Does will throw an error if we fix the underlying type issues.

As for the original problem, we probably need to make the service generic...

**Comment by thomasdax98** [comment]
@johnnyomair Done

**Review by johnnyomair — APPROVED** [review]

**Review by nsams — APPROVED** [review]
I don't want to approve this ts-expect-error mess :cry:

**Comment by nsams** [comment]
This problem would not exist if the entity was used directly. Maybe that could be a good option for the fixtures.

the service currently does

- check for reserved paths (can be ignored in fixtures?)
- check for duplicate paths (can be ignored in fixtures? or maybe do it in a validate service method?)
- handle the document input (not needed for fixtures)
- + of course the entity creation

**Comment by johnnyomair** [comment]
We could also add a default value in code 🤔

**Comment by nsams** [comment]
> We could also add a default value in code 🤔

true. is not a generic solution that works everywhere

**Pull request merged**
