### PR TITLE
Add CLI package

### PR DESCRIPTION
**Pull request by johnnyomair**
Adds a new `@comet/cli` package to bundle our various scripts in a common package. The generate-block-types script has been moved to the new package for demonstration purposes

### CODE REVIEW

**Comment by johnnyomair** [comment]
We should consider whether we want such a general purpose package for all our scripts. My primary concern is that we may have some issues with dependencies. For instance, the `generate-block-meta` script has a dependency on `@comet/api-blocks`.

**Review by kaufmo — APPROVED** [review]
Very cool :star_struck: nice work :+1:

**Comment by nsams** [comment]
> We should consider whether we want such a general purpose package for all our scripts.

what would be the alternative? specific packages (@comet/generate-block-types instead of @comet/cli?)

We should do some brainstorming what could be part of @comet/cli one day.

**Comment by johnnyomair** [comment]
> what would be the alternative? specific packages (@comet/generate-block-types instead of @comet/cli?)

Yes! Or the block type generation may be part of the respective `@comet/site-cms` and `@comet/admin-cms` packages.

**Comment by nsams** [comment]
> Or the block type generation may be part of the respective @comet/site-cms and @comet/admin-cms packages.

then we have 2 copies of the same, not ideal (though not as bad as having copies in all apps)

**Comment by johnnyomair** [comment]
@nsams please review and merge – thanks!

**Review by dkarnutsch — APPROVED** [review]

**Comment by nsams** [comment]
I would keep using prettier, although it is a generated file that must not be linted, devs still will look at it's contents.

I guess you changed that for dependency reasons - question is, if comet/cli package itself will be a dev dependency only - then it can have prettier dependency with no big issue.

**Comment by johnnyomair** [comment]
> I would keep using prettier, although it is a generated file that must not be linted, devs still will look at it's contents.

Fixed in c70f103005d2ab9e3a38e936724d66cfa322c51f

**Review by nsams — APPROVED** [review]

**Pull request merged**
