### PR TITLE
Admin Generator (Future): Allow setting `sortBy` in column config

### PR DESCRIPTION
**Pull request by jamesricky**
---

## PR Checklist

-   [x] Merge parent PR https://github.com/vivid-planet/comet/pull/2512
-   [x] Verify if the change requires a changeset. See [CONTRIBUTING.md](https://github.com/vivid-planet/comet/blob/HEAD/CONTRIBUTING.md)
-   [x] Link to the respective task if one exists: SVK-239

### CODE REVIEW

**Review by johnnyomair — COMMENTED** [review]
Shouldn't this option be only available for combination columns?

**Comment by nsams** [comment]
> Shouldn't this option be only available for combination columns?

imho it can be for all columns

**Comment by nsams** [comment]
> I could override sortBy for a price column to "title", then the sort buttons of the price column would work very unexpected

If I configure it unexpected, I expect unexpected things to happen :)

...you seem to have a strong opinion here, I don't.

**Comment by johnnyomair** [comment]
> ...you seem to have a strong opinion here, I don't.

IMO the generator config should in the best case prevent unexpected/illogical configurations. But if it's not easily possible, I'm fine with allowing it everywhere. However, it's odd that @jamesricky has to handle cases where this never makes any sense, for instance `actionsColumnSortBy`. 🤷🏼‍♂️

**Comment by jamesricky** [comment]
> Shouldn't this option be only available for combination columns?

I agree, doesn't make sense for any other columns, especially "actions", I'll change that 👍🏼

**Comment by jamesricky** [comment]
> Shouldn't this option be only available for combination columns?

Done in 206e645f7b3ff17a90f2c4eeba1e7dce5e7071fd

**Review by johnnyomair — APPROVED** [review]

**Review by nsams — APPROVED** [review]

**Comment by johnnyomair** [comment]
@jamesricky please **rebase** (dependent PR)

**Review by johnnyomair — APPROVED** [review]

**Review by nsams — APPROVED** [review]

**Pull request merged**
