### PR TITLE
COM-442: Cleanup peer dependencies

### PR DESCRIPTION
**Pull request by johnnyomair**
- [x] Add changeset (if necessary)

### CODE REVIEW

**Comment by johnnyomair** [comment]
I'm still unsure about some peer dependencies

- `express` and `@nestjs/platform-express`: Currently `@nestjs/platform-express` is a dev dependency, but should be a peer IMO
- `nestjs-console` is a peer dependency, but could be a normal dependency?

What do you think?

Targeting `next` because in theory there could be a breaking change, will test this in one of our customer projects.

**Review by thomasdax98 — DISMISSED** [review]

**Comment by nsams** [comment]
- ideally express should be optional (to allow fastify)
- i can Imagine that mixing nestjs-console major versions can cause problems, we are on the safe side with peerDependency

**Comment by johnnyomair** [comment]
So should we make `@nestjs/platform-express` a peer for now and try to enable switching to fastify later?

**Comment by johnnyomair** [comment]
> So should we make `@nestjs/platform-express` a peer for now and try to enable switching to fastify later?

Done: 6fa93e18d466303490567eee3e5bddebca76f02f

**Review by thomasdax98 — DISMISSED** [review]

**Comment by johnnyomair** [comment]
@nsams @thomasdax98 I've resolved conflicts, please review again.

**Review by thomasdax98 — APPROVED** [review]

**Pull request merged**
