### PR TITLE
Future Admin Generator: Use correct block for `Product.image`

### PR DESCRIPTION
**Pull request by Ben-Ho**
---

## PR Checklist

-   [x] Verify if the change requires a changeset. See [CONTRIBUTING.md](https://github.com/vivid-planet/comet/blob/HEAD/CONTRIBUTING.md)
-   [ ] Link to the respective task if one exists: 
-   [ ] Provide screenshots/screencasts if the change contains visual changes

<details>
    <summary>Screenshots/screencasts</summary>
    
</details>

### CODE REVIEW

**Review by johnnyomair — COMMENTED** [review]
Actually, the config of the form has a different block specified than the entity. Wouldn't it be better to fix the config and maybe add a validation in the future?

**Comment by nsams** [comment]
> Actually, the config of the form has a different block specified than the entity. Wouldn't it be better to fix the config and maybe add a validation in the future?

that is strange. I'll look into this.

**Review by nsams — APPROVED** [review]

**Comment by johnnyomair** [comment]
@Ben-Ho as discussed please fix the ProductForm config, even if it's not used anymore (at the current moment).

**Comment by Ben-Ho** [comment]
> as discussed please fix the ProductForm config, even if it's not used anymore (at the current moment).

this is fixed in #1908

**Pull request merged**
