### PR TITLE
api generator: In relation input support different target types instead of assuming uuid

### PR DESCRIPTION
**Pull request by nsams**
fixes test from #1285

Open question:

currently for Integer target types also graphl `ID` type is used.
- is this wanted
- is it even working (and converted by class-validator from string to number?)

### CODE REVIEW

**Review by johnnyomair — DISMISSED** [review]
We should still evaluate if using the `ID` type and the `@IsInt()` validator don't cause any issues.

**Comment by lllHuber** [comment]
I just tested the number types and GraphQL type `ID` alone is not enough. We need to add a class-transformer as well, or just use `Int` instead. Here are two solutions that work:

`@IsNullable()
    @Field(() => ID, { nullable: true })
    @IsInt()
    @Transform(({ value }) => parseInt(value))
    numberField?: number;`

or

`@IsNullable()
    @Field(() => Int, { nullable: true })
    @IsInt()
    numberField?: number;`

**Comment by nsams** [comment]
ok, thank you for testing this out.

what do you prefer?

**Comment by lllHuber** [comment]
I think that we should go with `ID` because it allows for a cleaner separation between api and admin/site/other clients. The `ID` doesn't care which data-type is used in the api and will always be consistent in the client (for example if the data type were to change in the api, it doesn't affect the client, but if we used type `Int` and later changed the ID to a uuid, all clients would have to be updated as well).

**Comment by nsams** [comment]
I added the transform now (IsInt I removed, because the transform makes sure only int passes thru)

**Comment by johnnyomair** [comment]
> I added the transform now (IsInt I removed, because the transform makes sure only int passes thru)

Are you sure? 😉 

image

**Review by johnnyomair — APPROVED** [review]

**Pull request merged**
