### PR TITLE
Fix comet-demo message ids

### PR DESCRIPTION
**Pull request by dkarnutsch**
all messages from comet-demo should start with "cometDemo", except a message from comet is used

### CODE REVIEW

**Review by johnnyomair — APPROVED** [review]
Developers shouldn't declare messages with `comet.*` directly in applications as these messages will be extracted to the app-specific files, resulting in duplicate messages. Maybe we need to expose generic messages from the library, like `export const okMessage = <FormattedMessage id="comet.generic.ok" defaultMessage="OK" />`. But this is something for another PR

**Comment by dkarnutsch** [comment]
> Developers shouldn't declare messages with `comet.*` directly in applications as these messages will be extracted to the app-specific files, resulting in duplicate messages. Maybe we need to expose generic messages from the library, like `export const okMessage = <FormattedMessage id="comet.generic.ok" defaultMessage="OK" />`. But this is something for another PR

Yes, I was thinking about that too. Possible solutions are:

1. Exporting all messages from the library (as you have stated)
- This makes development a bit tedious
- But this has the big benefit that you can see which translated strings the library is offering with looking at one file

2. Preventing comet.* inside the app
- Limiting parsing to a specific pattern is currently not supported by @formatjs/cli
- However, all messages not starting with the application prefix could be tossed before committing them to the lang repo. This would require a little custom script.

I would prefer 1. as this imposes less "magic" and I think this might result in less duplicated messages.
@nsams @kaufmo @fraxachun what do you think?

**Comment by nsams** [comment]
I like the (for me new) idea of exporting messages from the library. It will only work for `<FormattedMessage` and not for intl.formatMessage (for use cases where you need a string) though. We can probably ignore those not so common cases? (application message is required for those)

:two: has to be done in addition to :one:, possibly in the lint stage (if that is easier)

Alternative to :one: could be that we allow usage comet.* inside the app, but only for messages that are defined in comet library (a linter could check that). defaultMessage could be omitted. Pro: intrl.formatMessage would work.

**Comment by johnnyomair** [comment]
> It will only work for <FormattedMessage and not for intl.formatMessage (for use cases where you need a string) though.

We could try if exporting `MessageDescriptor`s, which can be used by both `<FormattedMessage {...descriptor} />` and `intl.formatMessage(descriptor)` would work as well. It'd be especially interesting whether Format.JS does extract those messages.

> Exporting all messages

I believe we should only export generic message that will used in application code, e.g. OK, Yes, Category etc. Messages specific to the library should not be exported.

> Alternative to 1️⃣ could be that we allow usage comet.* inside the app, but only for messages that are defined in comet library (a linter could check that). defaultMessage could be omitted. Pro: intrl.formatMessage would work.

I believe that Format.JS would still extract those messages to the app-specific file, which would result in duplicate definitions. Even if the translators do not translate messages starting with comet.*, translation services such as Lingohub would return empty strings for the translations. I don't know if Format.JS is smart enough to choose the actually translated message over the empty string.

**Pull request merged**
