### PR TITLE
Change default page size to match MUI Data Grid

### PR DESCRIPTION
**Pull request by fraxachun**
Warning is "MUI: The page size  is not preset in the Add it to show the pagination select."

### CODE REVIEW

**Review by johnnyomair — DISMISSED** [review]

**Comment by nsams** [comment]
With this change we remove the pageSize select by default.

The warning was shown when pageSize didn't match 10, 25, 50 or 100 (=default value of rowsPerPageOptions)?

**Comment by fraxachun** [comment]
> With this change we remove the pageSize select by default.
There is no pageSize-select by default.

> The warning was shown when pageSize didn't match 10, 25, 50 or 100 (=default value of rowsPerPageOptions)?
This is correct, but since the default value of pageSize is 20 the warning was shown until the pageSize was set manually to one of the default values.

Do you suggest something different?

**Comment by fraxachun** [comment]
> Yes: why not change the default pageSize to 25
You're right, this fits better to the default settings of the Data Grid. Changed.

**Comment by johnnyomair** [comment]
> Yes: why not change the default pageSize to 25

Should we change this in the API (and generator) as well?

**Comment by fraxachun** [comment]
Good idea! I added a commit which changes the the default value in the api.

**Review by johnnyomair — APPROVED** [review]

**Review by nsams — APPROVED** [review]

**Pull request merged**
