### PR TITLE
Add `hiddenForState` option to `createCompositeBlock`

### PR DESCRIPTION
**Pull request by SebiVPS**
## Description

This PR adds a `hiddenForState` function to the `createCompositeBlock` factory. This adds the possibility to hide a child block, depending on the state, for example, when multiple variants of a composite block are available and some settings are redundant for some of the variants.

## Example

For example usage see https://github.com/vivid-planet/comet/tree/createLayoutFactory

## Related tasks and documents

COM-1130

### CODE REVIEW

**Review by johnnyomair — COMMENTED** [review]
Didn't we decide that we reordering of the admin component parts would be preferable, and that we need a createLayoutBlockFactory anyway?

**Comment by SebiVPS** [comment]
> Didn't we decide that we reordering of the admin component parts would be preferable, and that we need a createLayoutBlockFactory anyway?

I do not think we would need a createLayoutBlockFactory, maybe #2699 is enough?

**Review by johnnyomair — COMMENTED** [review]
It would be nice if we had a usage of this in Demo.

**Comment by SebiVPS** [comment]
> It would be nice if we had a usage of this in Demo.

I see no good use case in existing blocks and would not add another block, just for this use case? I added an example to the changeset, is this enough?

**Review by johnnyomair — APPROVED** [review]

**Pull request merged**
