### PR TITLE
API Generator: Change default value for input field if property has no initializer

### PR DESCRIPTION
**Pull request by dkarnutsch**
Previously, the following property of an entity

```ts
@Property({ type: types.date, nullable: true })
@Field({ nullable: true })
availableSince?: Date;
```

resulted in the following input being generated:

```ts
@IsNullable()
@IsDate()
@Field({ nullable: true })
availableSince?: Date;
```

This was problematic for two reasons:

1.  The error message would be misleading when trying to create an entity without providing a value for the property. For example, a valid GraphQL mutation

    ```graphql
    mutation CreateProduct {
        createProduct(input: { title: "A", slug: "A", description: "FOO" }) {
            id
            availableSince
        }
    }
    ```

    would result in the following error:

    ```
    "isDate": "availableSince must be a Date instance"
    ```

2.  Relying on the initializer as the default value is not obvious and appears somewhat magical.

To address this, we now use `null` as the default value for nullable properties if no initializer is provided. If an initializer is provided, it is used as the default value.

---

While working on a different feature for the API generator, I noticed this strange behaviour, that you need to provide an initializer for the input to be valid as it must contain a default value.

With https://github.com/vivid-planet/comet/pull/1820 this was bypassed for demo.

Is this something we want to support? I think we should, but I'm not sure if it is that easy if it was bypassed in demo... 

This line must be modified:
`const defaultValue = prop.nullable && (initializer == "undefined" || initializer == "null") ? "null" : initializer;`

### CODE REVIEW

**Comment by johnnyomair** [comment]
> Is this something we want to support? I think we should, but I'm not sure if it is that easy if it was bypassed in demo...

Yes, we shouldn't require default values in the GraphQL schema for our code to work.

**Review by johnnyomair — COMMENTED** [review]
This is "only" a failing test, right? Do you plan to fix it yourself once we decide whether we want this or not?

**Comment by dkarnutsch** [comment]
> This is "only" a failing test, right? Do you plan to fix it yourself once we decide whether we want this or not?

Yes

**Comment by nsams** [comment]
Do I understand this correctly:

Currently the following creates a input dto with defaultValue=null:
```
    @Property({ type: "text", nullable: true })
    title?: string = undefined;
```

but you expected also this to have defaultValue=null:
```
    @Property({ type: "text", nullable: true })
    title?: string;
```

**Comment by dkarnutsch** [comment]
> Do I understand this correctly:
> 
> Currently the following creates a input dto with defaultValue=null:
> 
> ```
>     @Property({ type: "text", nullable: true })
>     title?: string = undefined;
> ```
> 
> but you expected also this to have defaultValue=null:
> 
> ```
>     @Property({ type: "text", nullable: true })
>     title?: string;
> ```

Exactly. Without the defaultValue our validators are not working correctly and the createMutation requires `title` even though it's nullable

**Comment by nsams** [comment]
> Without the defaultValue our validators are not working correctly

what is not working correclty?

> and the createMutation requires title even though it's nullable

yes, my thought was that just because a field is nullable, it doesn't necessarily doesn't mean that should be the default value. It would even not be possible to define a nullable field as required.

> With https://github.com/vivid-planet/comet/pull/1820 this was bypassed for demo.

yes, that's how the current implementation is intended to be used.

**Comment by johnnyomair** [comment]
> It would even not be possible to define a nullable field as required.

Is this something we want? Even reading this sentence is confusing to me 😅

**Comment by johnnyomair** [comment]
I didn't understand this correctly before: IMO an optional field in the database shouldn't add a default value in the GraphQL schema when there's no initializer. However, it should be possible to create an entity with an optional field when the respective GraphQL input field is undefined. Is this something we currently don't support?

**Comment by dkarnutsch** [comment]
## With initializer
The following entity definition
```ts
    @Property({ type: types.date, nullable: true })
    @Field({ nullable: true })
    availableSince?: Date = undefined;
```
creates this input
```ts
    @IsNullable()
    @IsDate()
    @Field({ nullable: true, defaultValue: null })
    availableSince?: Date;
```
## Without initializer
The following entity definition
```ts
    @Property({ type: types.date, nullable: true })
    @Field({ nullable: true })
    availableSince?: Date;
```
creates the following input
```ts
    @IsNullable()
    @IsDate()
    @Field({ nullable: true })
    availableSince?: Date;
```
which results in this mutation
```
mutation CreateProduct {
  createProduct(
    input: {
      title: "A"
      slug: "A"
      description: "FOO"
      type: Cap
      image: {
        attachedBlocks: [{ type: "pixelImage", props: {} }]
        activeType: "pixelImage"
      }
    }
  ) {
    id
    availableSince
  }
}
```
throwing this error
```js
"validationErrors": [
            {
              "target": {
                "title": "A",
                "status": "Unpublished",
                "slug": "A",
                "description": "FOO",
                "type": "Cap",
                "additionalTypes": [],
                "price": null,
                "inStock": true,
                "image": {
                  "attachedBlocks": [
                    {
                      "type": "pixelImage",
                      "props": {}
                    }
                  ],
                  "activeType": "pixelImage"
                },
                "discounts": [],
                "articleNumbers": [],
                "colors": [],
                "category": null,
                "tags": [],
                "tagsWithStatus": [],
                "manufacturer": null
              },
              "property": "availableSince",
              "children": [],
              "constraints": {
                "isDate": "availableSince must be a Date instance"
              }
            }
          ]
```

### My concerns
- the error message is misleading as `availableSince: null` would also be ok
- relying on the initializer as defaultValue is not obvious and some kind of magic

### Possible solutions
- setting `defaultValue: null` even though no initializer is provided
- adding `@IsUndefinable` if no initializer is provided is instead of `@IsNullable` (IMO this is better, but I did not think about that when creating the MR)

**Comment by nsams** [comment]
can we talk about this today?

**Comment by johnnyomair** [comment]
> setting defaultValue: null even though no initializer is provided

As discussed in today's JFX, please make this change.

**Review by johnnyomair — APPROVED** [review]

**Review by nsams — DISMISSED** [review]

**Review by johnnyomair — APPROVED** [review]

**Pull request merged**
