### PR TITLE
enable ts option declarationMap

### PR DESCRIPTION
**Pull request by nsams**
https://www.typescriptlang.org/tsconfig#declarationMap

This allows opening the source file when Ctrl+Click on an import of a library within the monorepo.

This is soo great when developing in comet demo

### CODE REVIEW

**Review by johnnyomair — APPROVED** [review]

**Comment by johnnyomair** [comment]
@nsams we need to exlude `*.d.ts` files from linting

**Comment by nsams** [comment]
hm, the error is for `.d.ts.map` files - don't we exclude `.d.ts` already?

**Comment by johnnyomair** [comment]
You're right, my bad. Then we need to exclude `*.d.ts.map` files 😁

**Comment by nsams** [comment]
ok, was not related to eslint but `formatjs extract` - which is also called during linting

**Comment by nsams** [comment]
I still would keep excluding lib from eslint

**Review by johnnyomair — APPROVED** [review]

**Comment by johnnyomair** [comment]
> I still would keep excluding lib from eslint

I believe we already do this (implicitly) by running the lint command only for `src/` directories.

**Comment by nsams** [comment]
>> I still would keep excluding lib from eslint
> I believe we already do this (implicitly) by running the lint command only for src/ directories.

the IDE doesn't know that and shows many non-helpful errors.

**Pull request merged**
