### PR TITLE
Add little helper muiGridPagingToGql to simplify data grid handling

### PR DESCRIPTION
**Pull request by dkarnutsch**
Motivation:
- avoids duplication
- nicer to read
- less error-prone

### CODE REVIEW

**Comment by dkarnutsch** [comment]
We could also discuss to streamline the api (options vs parameters), returning the property or only the value but this is out of scope for this PR

**Comment by nsams** [comment]
Imho this is not neccesary, as the "manual" implementation is so simple. One function call vs. one multiplication, I'd say the multiplication is easier to read and understand.

**Comment by dkarnutsch** [comment]
> Imho this is not neccesary, as the "manual" implementation is so simple. One function call vs. one multiplication, I'd say the multiplication is easier to read and understand.

Philosophically, what is necessary? I think it doesn't hurt and someone might prefer code that is replicated dozens of times to be as tight as possible to keep the focus on the things that matter.

**Comment by johnnyomair** [comment]
I think it's a good idea. I just recently came across some code where offset and limit behaved strangely, if I remember right due to wrong assumptions about whether the page is zero-based or one-based. Having a function that takes care of the calculation would eliminate the need to think about it every time.

One could also argue that it's strange that we have a  muiGridFilterToGql and muiGridSortToGql but no muiGridPagingToGql.

However, the usage of the proposed muiGridPagingToGql seems cumbersome to me. Maybe we could change it to:

```ts
...muiGridPagingToGql(dataGridProps),
```

or even create our own `pageModel`? To be honest, I don't really understand why DataGrid has a filterModel and a sortModel, but page and pageSize anyway.

**Comment by dkarnutsch** [comment]
> I think it's a good idea. I just recently came across some code where offset and limit behaved strangely, if I remember correctly due to wrong assumptions about whether the page is zero-based or one-based. Having a function that takes care of the calculation would eliminate the need to think about it every time.
> 
> One could also argue that it's strange that we have a muiGridFilterToGql and muiGridSortToGql but no muiGridPagingToGql.
> 
> However, the usage of the proposed muiGridPagingToGql seems cumbersome to me. Maybe we could change it to:
> 
> ```ts
> ...muiGridPagingToGql(dataGridProps),
> ```
> 
> or even create our own `pageModel`? To be honest, I don't really understand why DataGrid has a filterModel and a sortModel, but page and pageSize anyway.

@nsams how can we move forward here?

**Review by johnnyomair — APPROVED** [review]

**Pull request merged**
