### PR TITLE
New RTE Icons

### PR DESCRIPTION
**Pull request by thomasdax98**
- Add new icons intended to be used in the RTE to `@comet/admin-icons`
- Replace the current icons in the RTE toolbar with new icons from `@comet/admin-icons`
- Change how `maxVisible` in `FeaturesButtonGroup` works:
  - If maxVisible = 4 and there are four features -> all four features (and no dropdown) are shown
  - If maxVisible = 4 and there are five features -> three features and the dropdown (containing two features) are shown

### CODE REVIEW

**Comment by johnnyomair** [comment]
> Remove maxVisible from FeaturesButtonGroup

We explicitly added this for multiple custom inline styles, why remove it now?

**Comment by thomasdax98** [comment]
@johnnyomair Because it doesn't exist in the screen design

Bildschirmfoto 2023-10-25 um 10 07 11

**Review by johnnyomair — COMMENTED** [review]
Should we really change the link icon? This also change it in the page tree link document type. Isn't the new icon only for the RTE?

**Comment by thomasdax98** [comment]
> Should we really change the link icon? This also change it in the page tree link document type. Isn't the new icon only for the RTE?

True, I changed the icon back

**Review by johnnyomair — APPROVED** [review]

**Comment by johnnyomair** [comment]
@thomasdax98 could you please adapt this PR's description so it reflects the latest changes? This description will be used for the squashed commit's description

**Review by jamesricky — APPROVED** [review]

**Pull request merged**
