### PR TITLE
Fix inconsistent null/undefined usage in OneOf block

### PR DESCRIPTION
**Pull request by nsams**
alternative to https://github.com/vivid-planet/comet/pull/1060

### CODE REVIEW

**Review by johnnyomair — COMMENTED** [review]
I've thought about changing it in the OneOfBlock too. In existing blocks, activeType can be `null`, but this shouldn't be a problem when using falsy conditions. Are we okay with this?

**Comment by nsams** [comment]
> In existing blocks, activeType can be null

yes, that changes with with PR. But that didn't match the types anyway.

**Review by johnnyomair — APPROVED** [review]

**Review by johnnyomair — APPROVED** [review]

**Comment by johnnyomair** [comment]
I've tested this locally with existing blocks it works perfectly fine.

But I've noticed something very interesting: The `activeType` is still existing in the database and has the value `null`. I did some further digging and came to the conclusion that this caused by a) our `transformToSave` returning `{ "key": undefined }` for undefined values and MikroORM (or Postgres) converting `{ "key": undefined }` to `{ "key": null }` in order to be valid JSON. We could fix this by omitting undefined values in transformToSave (I've already successfully tested that) – but should we?

**Comment by nsams** [comment]
> We could fix this by omitting undefined values in transformToSave (I've already successfully tested that) – but should we?

yes, I think we should. Either we use null (and type accordingly) or undefined. There should be no mixture where types are not 100% correct.

(I also changed that - didn't test though - I hope my implementation is similar enough to yours)

**Comment by johnnyomair** [comment]
> (I also changed that - didn't test though - I hope my implementation is similar enough to yours)

This should work for the OneOf block. I was rather thinking of a general solution in `transformToSave`

image

**Comment by nsams** [comment]
good idea, I force pushed away mine, please add yours.

**Comment by johnnyomair** [comment]
> good idea, I force pushed away mine, please add yours.

Done

**Review by johnnyomair — DISMISSED** [review]

**Review by johnnyomair — APPROVED** [review]

**Pull request merged**
