### PR TITLE
API: Extend StringFilter to support comparison operators

### PR DESCRIPTION
**Pull request by dkarnutsch**
---

## PR Checklist

-   [x] Verify if the change requires a changeset. See [CONTRIBUTING.md](https://github.com/vivid-planet/comet/blob/HEAD/CONTRIBUTING.md)

### CODE REVIEW

**Review by johnnyomair — COMMENTED** [review]
I'm curious: Why can't you use. [DateFilter](https://github.com/vivid-planet/comet/blob/next/packages/api/cms-api/src/common/filter/date.filter.ts#L5) for this?

**Comment by dkarnutsch** [comment]
> I'm curious: Why can't you use [DateFilter](https://github.com/vivid-planet/comet/blob/next/packages/api/cms-api/src/common/filter/date.filter.ts#L5) for this?

ISO Dates are just one use case, you can also think about a few others. E.g. you create a contact list and you want to display all contacts with names starting from a to f.

But to answer your question. Suppose you have the following entity:
```ts
class Event {
  @Field()
  @Property({columnType: date})
  start: string;
}
```

For `start` I want to only have a date without any time. For this I use the appropriate psql column type `date` (https://www.postgresql.org/docs/current/datatype-datetime.html). This type has to be mapped to `string` in TS, because otherwise I have all the timezone issues. Storing ISO dates as string is very handy, because you can lexicographically order them and filter them using string operations without thinking about timezones. And GraphQL has no type for dates without time. All resolvers/dtos are generated by our admin generator, so I have no easy option to overwrite something.

**Comment by nsams** [comment]
The current implementation is specially made to be used in combination with mui-x data-grid where strings have the following default filters: https://github.com/mui/mui-x/blob/5585ea10bae52c69fd1cd1737d1b25e731d7d5b2/packages/x-data-grid/src/colDef/gridStringOperators.ts#L23

**Comment by dkarnutsch** [comment]
> The current implementation is specially made to be used in combination with mui-x data-grid where strings have the following default filters: https://github.com/mui/mui-x/blob/5585ea10bae52c69fd1cd1737d1b25e731d7d5b2/packages/x-data-grid/src/colDef/gridStringOperators.ts#L23

But additional options, only used on the API side, should do no harm, right?

In my use case case I don't have a grid as client. But the API generator would work for my use case really well.

**Comment by nsams** [comment]
> But additional options, only used on the API side, should do no harm, right?

Yes. Still we should discuss if it is the best solution.

> And GraphQL has no type for dates without time.

Yes, but I think you should use https://the-guild.dev/graphql/scalars/docs/scalars/date. And that could also have it's own Filter type.

**Comment by dkarnutsch** [comment]
> > But additional options, only used on the API side, should do no harm, right?
> 
> Yes. Still we should discuss if it is the best solution.
> 
> > And GraphQL has no type for dates without time.
> 
> Yes, but I think you should use https://the-guild.dev/graphql/scalars/docs/scalars/date. And that could also have it's own Filter type.

I've made an RFC for `graphql-scalars` in #2124

**Pull request closed without merging**
