### PR TITLE
Demo Site: add redis (with sentinel) cache-handler with fallback using ioredis

### PR DESCRIPTION
**Pull request by nsams**
This adds redis to demo site.

- using ioredis as that supports redis sentinel ou tof the box
- not using @neshca/cache-handler, as that does not ioredis (and so doesn't support sentinel)
- this has a fallback mode that (temporarily) switches to a local in-memory cache
    - if redis client is not ready
    - additionally using a try-catch

TODO:
- [ ] eventually remove redis (or make optional) in local dev
- [ ] test in a deployment

### CODE REVIEW

**Review by dkarnutsch — APPROVED** [review]
It works nicely in a deployed environment 👍 

Future improvements:
- Add a DEBUG flag to enable logging
- Format file with eslint/prettier

**Review by johnnyomair — COMMENTED** [review]
Should we merge this now or wait for an decision whether we want to use sentinel or not?

**Comment by nsams** [comment]
should we have redis at all for local development?

**Comment by dkarnutsch** [comment]
I would use it in development as well. Development should be close to production, but I'm not sure how useful it is in dev mode...

**Comment by johnnyomair** [comment]
Maybe with a feature flag to optionally enable it for testing? Probably not useful in Demo, but in some of our projects.

**Comment by dkarnutsch** [comment]
> * comment out redis in docker-compose file

sounds good 👍 , similar to what we have for developing the kubernetes modules

I would also do the same for the starter.

**Comment by johnnyomair** [comment]
> always start redis and just don't use it

I'd be okay with that. But commenting out redis is also fine

**Comment by johnnyomair** [comment]
Superseded by #2596.

**Pull request closed without merging**
