### PR TITLE
Add a `RadioField` component to make it easier to create radio fields in final forms

### PR DESCRIPTION
**Pull request by jamesricky**
This is basically the same as the existing `CheckboxField` component: [CheckboxField.tsx](https://github.com/vivid-planet/comet/blob/2b68513bebcab1f61b1d04d7051ab839d33cafba/packages/admin/admin/src/form/fields/CheckboxField.tsx). 

---

## PR Checklist

-   [x] Verify if the change requires a changeset. See [CONTRIBUTING.md](https://github.com/vivid-planet/comet/blob/HEAD/CONTRIBUTING.md)
-   [x] Link to the respective task if one exists: COM-995

### CODE REVIEW

**Review by johnnyomair — COMMENTED** [review]
What do you think about about this alternative implementation?

```tsx
<RadioField 
  name="radio" 
  label="Radio"
  options={[{ label: "Option One", value: "option-one" }, ...]}
/>
```

This would be even easier to integrate into applications, but it's different to the other field components.

**Comment by jamesricky** [comment]
> What do you think about about this alternative implementation?
> 
> ```tsx
> <RadioField 
>   name="radio" 
>   label="Radio"
>   options={[{ label: "Option One", value: "option-one" }, ...]}
> />
> ```
> 
> This would be even easier to integrate into applications, but it's different to the other field components.

Yes 👍🏼 
I wanted to add this `RadioField` first so it's similar to the existing `CheckboxField` and then add both, a `CheckboxListField` and a `RadioListField` in a follow-up PR. 

But since there's never really a single (non-list) radio input your suggestion would probably be better. 

Should this maybe be called `RadioListField` then, instead of `RadioField`, so it's more obvious and consistent with the future `CheckboxListField`?

**Comment by johnnyomair** [comment]
> Should this maybe be called `RadioListField` then, instead of `RadioField`, so it's more obvious and consistent with the future `CheckboxListField`?

I'd probably go with `RadioGroupField`, which is more in line with the "official" naming: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio

**Comment by jamesricky** [comment]
Closed in favor of https://github.com/vivid-planet/comet/pull/2400

**Pull request closed without merging**
