### PR TITLE
Add AffectedArg-decorator

### PR DESCRIPTION
**Pull request by fraxachun**
Current situation is that when a scope-argument is present in a graphql-request this is used to check the content scope. However, in certain situations (e.g. the ContentScope only has one field) we just want to submit the value instead of a scope-Object:
```
    @Query(() => Customers)
    @AffectedArg((tenantId: string) => ({tenantId}))
    async customersForTenant(@Args("tenantId") tenantId: string): Promise<PaginatedNews> {
```

### CODE REVIEW

**Comment by nsams** [comment]
please add usage examples to the description of this PR

**Comment by nsams** [comment]
Why not use `@AffectedEntity(Teanent, { idArg: "teanentId"});` together with `@ScopedEntity` in Teanent entity?

**Comment by johnnyomair** [comment]
Wasn't our intention to remove the `scope` arg magic and make it explicit? Something like `@AffectedArg("scope")`?

**Comment by johnnyomair** [comment]
> Do you?

No.

The "problem" that still remains that if developers send a `scope` arg, they may assume that everything is validated correctly, where it may not be. For example:

```tsx
updateTenant(
  scope: { tenantId: "123" }, // ID of the parent tenant
  id: "456" // Actual ID of the tenant
)
```

This operation will be allowed if a user has access to the parent tenant, but will not verify if a user can access the child tenant. I thought this is what we we're talking about last week.

**Pull request closed without merging**
