### PR TITLE
Add workflow to create 'Merge main into next' PR automatically

### PR DESCRIPTION
**Pull request by johnnyomair**
Thanks for the inspiration!

Initial implementation by ChatGPT: https://sharegpt.com/c/URpFwHh

### CODE REVIEW

**Comment by johnnyomair** [comment]
This only works if the merge works without conflicts. Should we always create a PR, including merge conflicts?

**Review by nsams — APPROVED** [review]
what happens if there is a conflict?

**Comment by johnnyomair** [comment]
> what happens if there is a conflict?

The workflow fails and no PR is created

**Comment by johnnyomair** [comment]
@nsams I've changed the workflow to also create a PR if there's a conflict: f9fd752e93e565038e452be0324f5820b27bbf09

**Comment by johnnyomair** [comment]
See https://github.com/johnnyomair/test-auto-pr/pull/1 for an example

**Comment by nsams** [comment]
could you change the PR body in conflict case to something that explains what to do?

**Comment by johnnyomair** [comment]
> could you change the PR body in conflict case to something that explains what to do?

Done bd5cee8ba7cde207d3569459cca4a166faf09655.

**Review by nsams — APPROVED** [review]

**Pull request merged**
