### PR TITLE
Remove role- and rights-field as it is opinionated

### PR DESCRIPTION
**Pull request by fraxachun**

### CODE REVIEW

**Comment by nsams** [comment]
I thought something opinionated for our IDP/idp-proxy setup is intentional? Or is it always a bit different?

**Comment by fraxachun** [comment]
The current plannings for user permission are completely different than this role/rights here. Moreover it is quite easy to overwrite the interface and this should take place in the starter.

**Review by johnnyomair — COMMENTED** [review]
Some of our applications are relying on this feature. How would they implement it?

1. Extend the current user interface
2. Create a custom AllowForRole decorator
3. Create a custom RoleGuard

Could we still provide the decorator and guard but remove them from the global Comet guard?

**Comment by fraxachun** [comment]
Since the update to next is breaking anyway I think it is okay to have to implement this in the application and btw the AllowForRole-decorator is hardly used. I think our planned user-management package will be the way to go even though it will still take some time until it is ready to use.

**Comment by fraxachun** [comment]
Superseded by https://github.com/vivid-planet/comet/pull/1149Sup

**Pull request closed without merging**
