### PR TITLE
Support scope in admin-generator

### PR DESCRIPTION
**Pull request by Ben-Ho**

### CODE REVIEW

**Comment by nsams** [comment]
detail query, uplodate mutation and delete mutation never have a scope argument, only list query and create mutation can have it. And it must be fully optional (no scope related code generated when there is no scope)

**Comment by Ben-Ho** [comment]
> detail query, uplodate mutation and delete mutation never have a scope argument, only list query and create mutation can have it. And it must be fully optional (no scope related code generated when there is no scope)

Alright, updated! Scope related code only added if needed. 👍

**Review by nsams — COMMENTED** [review]
You need a way to test this in demo. News do have a scope, they could be used with future generator similar to products (one page generator v1, one page v2)

Then you will see that update/detail query have no scope arg

**Comment by Ben-Ho** [comment]
> You need a way to test this in demo. News do have a scope, they could be used with future generator similar to products (one page generator v1, one page v2)
> 
> Then you will see that update/detail query have no scope arg

Alright, I'll add this. 👍 But I still need this also for update/detail. Today I discussed this topic with @fraxachun and that the common use-case should use AffectedEntity and ScopedEntity, but in my case adding a scope parameter makes my code much easier.

And I think admin-generator code does not become much more complex by adding this similar lines.

But if you like to we can discuss this in person and I'll show you what @fraxachun and I tried. Maybe you got some idea how to solve my problem easy with ScopedEntity...

**Comment by nsams** [comment]
Yes, lets discuss this.

**Comment by Ben-Ho** [comment]
closed for #1696, and even #1696 wont be needed after refactoring project

**Pull request closed without merging**
