### PR TITLE
API Generator: Add support for disabling sort/filter using the `@CrudField()` decorator for embeddables

### PR DESCRIPTION
**Pull request by kaufmo**
## Description

Previously, it was not possible to disable sort/filter for all embedded fields by using the `@CrudField()` decorator on the embeddable, like here:

```ts
@Embedded(() => Foo)
@CrudField({ sort: false, filter: false, input: false })
foo: Foo;
```

It only worked for fields inside `Foo˚. This PR adds support for using the decorator for the whole embeddable.

### CODE REVIEW

**Review by johnnyomair — COMMENTED** [review]
@nsams general feedback regarding the unit tests for the API Generator: They're hard to read since there's a lot of setup. Also, the assert are usually "is valid file", but shouldn't they be something like "doesn't create a sort field"?

**Comment by nsams** [comment]
@kaufmo I pushed the implementation that fixes your tests into this PR

**Comment by nsams** [comment]
> general feedback regarding the unit tests for the API Generator: They're hard to read since there's a lot of setup.

I don't see a way how the setup could be simplified. Actually I really like the tests, they cover a lot of cases, developing the generator without them would be much more difficult.

> Also, the assert are usually "is valid file", but shouldn't they be something like "doesn't create a sort field"?

yes, absolutely

**Comment by johnnyomair** [comment]
> I don't see a way how the setup could be simplified. Actually I really like the tests, they cover a lot of cases, developing the generator without them would be much more difficult.

I didn't mean to write less tests or get rid of them. I just meant maybe we can improve the setup to reduce the cognitive load when reviewing the tests. I'll make a proposal someday 😉

**Review by johnnyomair — APPROVED** [review]

**Pull request merged**
