### PR TITLE
Add manufacturer country API to Demo

### PR DESCRIPTION
**Pull request by Ben-Ho**

### CODE REVIEW

**Review by johnnyomair — COMMENTED** [review]
Why isn't it possible to generate this API?

**Comment by Ben-Ho** [comment]
> Why isn't it possible to generate this API?

I didn't tried it.

**Comment by johnnyomair** [comment]
> I didn't tried it.

Please give it a try. As you know, we want to go _Generator First_.

**Comment by Ben-Ho** [comment]
> Please give it a try. As you know, we want to go _Generator First_.

It worked. For api-generator to work id-field is required so I renamed country to id.

**Review by nsams — APPROVED** [review]

**Review by johnnyomair — COMMENTED** [review]
Those three DTO files that aren't generate seem like leftovers to me. Can we delete them?

**Review by nsams — APPROVED** [review]

**Review by johnnyomair — APPROVED** [review]

**Pull request merged**
