### PR TITLE
Add `ContentOverflow` component

### PR DESCRIPTION
**Pull request by jamesricky**
---

COM-162

https://github.com/vivid-planet/comet/assets/6264317/11ff31f3-0ee1-4007-888d-c39c187b7348

### CODE REVIEW

**Comment by jamesricky** [comment]
FYI: I am open to suggestions for a better name 😅

**Comment by johnnyomair** [comment]
@jamesricky we decided to move all documentation to Docusaurus (see Field Set). Could you try moving the OverflowDialog docs as well? You feedback regarding our Story component would be valuable.

**Comment by johnnyomair** [comment]
> FYI: I am open to suggestions for a better name 😅
> 
> _Update: Maybe `DialogPreview`, `DialogSummary` or `ContentSummary` 🤔_

Maybe we could remove Dialog from the name, since it's an implementation detail? Could be a collapsible in a future change? What do you think of `OverflowingContent`?

**Comment by jamesricky** [comment]
> Maybe we could remove Dialog from the name, since it's an implementation detail? Could be a collapsible in a future change?

True 👍🏼 

> What do you think of OverflowingContent?

Don't really like the word `Overflowing` 😅 

Maybe `ContentPreview`? 🤔

**Comment by johnnyomair** [comment]
> Don't really like the word `Overflowing` 😅

👍🏼 

> Maybe `ContentPreview`? 🤔

We already have `SitePreview` and `BlockPreview`. I'm not sure if `ContentPreview` is too generic 🤔

**Comment by johnnyomair** [comment]
@jamesricky we discussed the name with UX internally, please rename to `ContentOverflow`.

**Comment by jamesricky** [comment]
> @jamesricky we decided to move all documentation to Docusaurus (see Field Set). Could you try moving the OverflowDialog docs as well? You feedback regarding our Story component would be valuable.

I'm doing this in a separate PR: #1869

**Review by johnnyomair — APPROVED** [review]

**Pull request merged**
