### PR TITLE
Admin Generator (Future): Allow Grid independent of Stack: Inject add and edit button from outside

### PR DESCRIPTION
**Pull request by Ben-Ho**
- Add new config-options toolbarActionProp and rowActionProp, because this shouldn't be the most common case
- Allows providing a complete button, besides changing the default stack-page behavior this also enables renaming the button which is often linked.
- If toolbarActionProp or rowActionProp is enabled but the prop is not set no button is rendered. This allows using the same grid like a grid with `{ ..., add: false, ...}` and `add: true` configuration at the same time.

### CODE REVIEW

**Review by johnnyomair — COMMENTED** [review]
What do you think about using the name actions instead of buttons?

`actionsProps: true`

`toolbarActions` or `primaryAction`

`rowAction`

Would be more versatile

**Comment by Ben-Ho** [comment]
> What do you think about using the name actions instead of buttons?

this could probably lead to confusion with https://github.com/vivid-planet/comet/pull/1913. But one of the two buttons is actually an action-button... what do you think about `navigationButtonProps`?

Or your example `primaryActionProp` | `toolbarActionProp` and `rowActionProp` but allow setting them separately.

**Comment by johnnyomair** [comment]
> what do you think about `navigationButtonProps`?

This would imply that it must always be a button and a navigation, while it doesn't have to be either IMO.

> Or your example primaryActionProp | toolbarActionProp and rowActionProp but allow setting them separately.

Would be okay for me.

@nsams what do you think?

**Comment by Ben-Ho** [comment]
> > Or your example primaryActionProp | toolbarActionProp and rowActionProp but allow setting them separately.
> 
> Would be okay for me.

then I'll go with toolbarActionProp and rowActionProp because it contains the location. and primary is defined by styling so this isn't correct either.

**Review by nsams — APPROVED** [review]

**Review by johnnyomair — APPROVED** [review]

**Pull request merged**
