### PR TITLE
Fix Drag and Drop on mobile devices

### PR DESCRIPTION
**Pull request by jomunker**
---

This is done by adding a [multi-backend DnD provider](https://www.npmjs.com/package/react-dnd-multi-backend?activeTab=readme) and a [html5 to touch pipeline](rdndmb-html5-to-touch) package. Both are used in the `App.tsx`. The result was tested in normal chrome, the chrome mobile mode, on an android smartphone on chrome and in Safari on both an iPhone and an iPad.

## PR Checklist
-   [x] Link to the respective task if one exists: COM-860
-   [x] Provide screenshots/screencasts if the change contains visual changes

<details>
    <summary>Screenshots/screencasts</summary>
    

### Desktop

https://github.com/vivid-planet/comet/assets/56400587/353547ae-9029-4f62-9063-5b0ad7422bd6

## Mobile (iPad)

https://github.com/vivid-planet/comet/assets/56400587/66dcba21-39cd-4b6d-af05-bd3b7f322883

</details>

### CODE REVIEW

**Comment by johnnyomair** [comment]
Why doesn't this PR target `main`? And we also need this in Starter.

@nsams what do you think about moving the DndProvider to the library and wrap the areas where it's needed (e.g., page tree). Would this even work?

**Comment by nsams** [comment]
but then we need to add the provider also eg. where we have forms with blocks. (blog ordering is also done using react-dnd, right?)

**Comment by johnnyomair** [comment]
> but then we need to add the provider also eg. where we have forms with blocks. (blog ordering is also done using react-dnd, right?)

Yes, but we could wrap the BlocksBlock, ListBlock etc. with the dnd provider. No need to wrap the complete application

**Comment by nsams** [comment]
Does this work and is this recommended? I mean why does this provider even exist?

**Review by dkarnutsch — APPROVED** [review]

**Comment by jomunker** [comment]
They recommend putting it next to the app root: https://arc.net/l/quote/kiozvjus

**Review by johnnyomair — APPROVED** [review]

**Review by thomasdax98 — APPROVED** [review]

**Pull request merged**
