### PR TITLE
Merge `@comet/blocks-api` into `@comet/cms-api`

### PR DESCRIPTION
**Pull request by johnnyomair**
## Description

The dedicated `@comet/blocks-api` package was originally introduced to support projects without CMS parts.
It turned out that this is never the case, so the separation doesn't make sense anymore.
Therefore, the `@comet/blocks-api` is merged into the `@comet/cms-api` package.

## Example

-   [x] I have verified if my change requires an example

## Changeset

-   [x] I have verified if my change requires a changeset

## Related tasks and documents

Task: https://vivid-planet.atlassian.net/browse/COM-1120

## Further information

The first commit merges the packages, the other commits add some improvements.

### CODE REVIEW

**Comment by johnnyomair** [comment]
<details>
<summary>List of newly added exports</summary>

- AnnotationBlockMeta 
- BaseBlocksBlockItemData
- BaseBlocksBlockItemInput
- BaseListBlockItemData 
- BaseListBlockItemInput 
- BaseOneOfBlockData
- BaseOneOfBlockInput
- BaseOneOfBlockItemData
- BaseOneOfBlockItemInput
- Block
- BlockContext
- BlockData
- BlockDataFactory
- BlockDataInterface
- BlockDataMigrationVersion
- BlockFactoryNameOrOptions
- BlockField 
- BlockIndexData
- BlockInput
- BlockInputFactory
- BlockInputInterface
- BlockMetaField
- BlockMetaFieldKind
- BlockMetaInterface
- BlockMetaLiteralFieldKind
- BlockMigration
- BlockMigrationInterface
- BlocksBlockFixturesGeneratorMap
- BlockTransformerServiceInterface
- ChildBlock 
- ChildBlockInput
- ColumnsBlockFactory
- composeBlocks
- createBlock
- createBlocksBlock
- createListBlock
- createOneOfBlock
- CreateOneOfBlockOptions
- createOptionalBlock 
- createRichTextBlock 
- createSpaceBlock 
- createTextLinkBlock 
- ExternalLinkBlock 
- ExtractBlockData
- ExtractBlockInput
- ExtractBlockInputFactoryProps
- FlatBlocks
- getBlocksMeta
- getFieldKeys
- getMostSignificantPreviewImageUrlTemplate
- getPreviewImageUrlTemplates
- getRegisteredBlocks
- getSearchText
- inputToData
- isBlockDataInterface
- isBlockInputInterface
- OneOfBlock
- OptionalBlockInputInterface 
- registerBlock
- RootBlock
- RootBlockEntity
- SearchText
- SimpleBlockInputInterface
- SpaceBlock
- strictBlockDataFactoryDecorator
- strictBlockInputFactoryDecorator
- TransformResponse
- TransformResponseArray
- transformToSave
- transformToSaveIndex
- TraversableTransformResponse
- TraversableTransformResponseArray
- typesafeMigrationPipe
- WeightedSearchText

</details>

**Comment by nsams** [comment]
aren't those block specific?

- TransformResponse
- TransformResponseArray
- transformToSave
- transformToSaveIndex
- TraversableTransformResponse
- TraversableTransformResponseArray

**Comment by johnnyomair** [comment]
> aren't those block specific?

You're right, I'll rename those as well

**Review by nsams — APPROVED** [review]

**Review by thomasdax98 — APPROVED** [review]

**Comment by johnnyomair** [comment]
@fraxachun do you want to review this?

**Pull request merged**
