### PR TITLE
Set default generatorOptions for create, update and delete if undefined (generate-crud.ts: generateCrud function)

### PR DESCRIPTION
**Pull request by VP-DS**
https://github.com/vivid-planet/comet/pull/1674#discussion_r1482644757

### CODE REVIEW

**Comment by VP-DS** [comment]
> Why so many changes in Tests?

@nsams I added **`create: true, update: true, delete: true`** to all calls of generateCrud that did not set them to make sure the variables are set in case they are needed.

Screenshot 2024-02-08 at 13 28 16

**Comment by nsams** [comment]
Please dont change that, find a different solution.

And you are still midifying the obj in metadata

**Comment by VP-DS** [comment]
> Please dont change that, find a different solution.
> 
> And you are still midifying the obj in metadata

Ah right, now it does not modify the const.

as for not changing the test files. don't know if there is a different solution other then adding

`const update = generatorOptions.update ?? true; ...`in the generate-crud.ts and use those variable here instead:

https://github.com/vivid-planet/comet/pull/1674/files#diff-e801c6222494414cd200139c942575ca42d7e25e3dbd1250b5017d3369e671fbR985

**Comment by nsams** [comment]
> const update = generatorOptions.update ?? true; ...in the generate-crud.ts and use those variable here instead:

perfect!

> ... but what is wrong with adding it to the tests generateCrud call params?

it's just an unneded change, why should you add it?

**Comment by VP-DS** [comment]
> > const update = generatorOptions.update ?? true; ...in the generate-crud.ts and use those variable here instead:
> 
> perfect!
> 
> > ... but what is wrong with adding it to the tests generateCrud call params?
> 
> it's just an unneded change, why should you add it?

Ok, I now kept the adjusting of the default values for create, update, delete in the generate-crud.ts generateCrud function, just created a a new object to not modify the received function params.

f668cba1f45fa75faf1a1e3eb03e972f893816bb

**Review by nsams — APPROVED** [review]

**Comment by nsams** [comment]
please always let all set reviewers approve before merging, thank you

**Pull request merged**
