### PR TITLE
Add FullHeightBox-component

### PR DESCRIPTION
**Pull request by fraxachun**

### CODE REVIEW

**Comment by fraxachun** [comment]
Do we want components like these or is there another way to achieve simplifying full-height boxes? Or is the current way good enough?

**Comment by nsams** [comment]
:+1:

I'd add page into the name, as this can be used at page level only. (Or do we have a mor specific name for this?)

`PageFullHeight`

**Comment by fraxachun** [comment]
> PageFullHeight
Since it is a Mui-Box I would keep `Box` in the name. But another solution just came into my mind, we could simply add a `fullheight`-prop to `MainContent` instead creating an additional component. How about that?

**Comment by jamesricky** [comment]
> Since it is a Mui-Box I would keep `Box` in the name. But another solution just came into my mind, we could simply add a `fullheight`-prop to `MainContent` instead of creating an additional component. How about that?

I'd also prefer the `MainContent` prop over a separate component, maybe it even makes sense to always make `MainContent` span over the full height by default, with `min-height`. 

> `height: calc(100vh - var(--comet-admin-master-layout-content-top-spacing))`

As @johnnyomair [mentioned internally](https://vividplanet.slack.com/archives/C052UQJ5DLN/p1683790835773539?thread_ts=1683789856.643009&cid=C052UQJ5DLN) using this height will not work on pages that render a `Toolbar` above the `MainContent`, as the Toolbar-height is not accounted for here. 

We could probably change the way we use the `Toolbar` by always rendering it inside `MainContent` and add custom styling for `Toolbar` inside `MainContent` to prevent spacing around the `Toolbar`.

**Pull request closed without merging**
